### ISSUE TITLE
Sticky item is backing to top when reach the end

### ISSUE THREAD

**Issue by renatorib** [leafo/sticky-kit#112]
I'm not sure why it occurs, can anyone help me?

Normal (OK): 
![image](https://cloud.githubusercontent.com/assets/3277185/8499141/c2ee40b4-2165-11e5-95e9-7966586e9b5d.png)

Scrolling (OK):
![image](https://cloud.githubusercontent.com/assets/3277185/8499149/def382ec-2165-11e5-9466-2110202db4a9.png)

When reach the end (it back to the top):
![image](https://cloud.githubusercontent.com/assets/3277185/8499171/0e8183f6-2166-11e5-8ec0-ce9e5f2ccf01.png)

The container is bootstrap .row and the sticky element is a .col, what mean this is fluid and float. Can be because it?

**Comment by corinnekunze** [comment]
@renatorib This issue sounds similar to the issue I was having. I am using bootstrap as well and when my column would hit the bottom of the row it would jump back up to the top. 

The reason this was happening for me is that sticky-kit is wrapping the column in a 'spacer' div that had a 'position: relative' css attribute when we actually wanted it to be on the row. When we look at the css that's added to the column after it has bottomed out, it should be useful if the position relative was on the row parent instead of this spacer div. That way the css that's written on the column... position: absolute, bottom: 0, etc. Will be useful to jump it to the bottom of the row container.

Anyway, short answer - had to come in to the source code to edit this but this worked for me to comment this out like so: (line 67-69 of unminified js)
```
// if (spacer) { // this is commmented out from original source code
  //   spacer.css('position', elm.css('position'));
// }
```

**Comment by schmeiserd** [comment]
Thanks for the solution, @corinnekunze !
I opened a pull request (https://github.com/leafo/sticky-kit/pull/115) to make this disabling optional...

**Comment by p-saovapakhiran** [comment]
@corinnekunze  Thanks so much! You saved my life!

**Comment by neotropic2023** [comment]
Thanks, this really helped!
The utterly most confusing of all of this... when live, using ({spacer:false}) as an option now, it works fine. However on localhost.... it moves it to the far side of the other element. Removing spacer, it does not, but jumps to the top again when you hit the bottom. Really, really odd behavior on the different environments.

Any ways, this helps. Onto next issue!

**Comment by leafo** [comment]
Sorry for the late response. In this case it's probably appropriate to remove the spacer with `spacer: false`. More on reference manual: http://leafo.net/sticky-kit/#reference

**Comment by leecollings-sb** [comment]
@leafo using `spacer:false` doesn't fix this issue, commenting out the lines as per @corinnekunze's response does create the correct behaviour.
