### ISSUE TITLE
Can not scroll to bottom

### ISSUE THREAD

**Issue by tatol** [leafo/sticky-kit#249]
Hello! Help please with my problem. I have code example here [link](https://jsfiddle.net/rzyso90g/3/) (it is only played on the big screen eg 1920*1080). I can not scroll to bottom, I am thrown back. If i enable spacer by default it is ok. But i do not need default spacer.
How can I solve this problem?

**Comment by stracker-phil** [comment]
Hi tatol

This is a layout issue and not caused by the sticky plugin...
The "bug" is, that the sticky-header is around 600 pixel high, and as soon as it sticks to the top, the actual body is reduced by 600 pixel (this causes the sudden change in the scrollbar).

You can simply fix this via CSS: Make the header `position:absolute` and add `top-margin: 650px` to the parent container.

**Comment by tatol** [comment]
thanks, it helped me
